import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './Design/**/*.{html,htm}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1c1b1b',
        'on-primary-container': '#858383',
        'primary-fixed': '#e5e2e1',
        'primary-fixed-dim': '#c8c6c5',
        'on-primary-fixed': '#1c1b1b',
        'on-primary-fixed-variant': '#474646',
        secondary: '#5e5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e3e2e2',
        'on-secondary-container': '#646464',
        'secondary-fixed': '#e3e2e2',
        'secondary-fixed-dim': '#c7c6c6',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#464747',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#390c00',
        'on-tertiary-container': '#e15724',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb59d',
        'on-tertiary-fixed': '#390c00',
        'on-tertiary-fixed-variant': '#832600',
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#444748',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#5f5e5e',
        outline: '#747878',
        'outline-variant': '#c4c7c7',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['3.5rem', { lineHeight: '3.75rem', letterSpacing: '-0.035em', fontWeight: '500' }],
        'headline-md': ['2.25rem', { lineHeight: '2.625rem', letterSpacing: '-0.025em', fontWeight: '500' }],
        'headline-sm': ['1.5rem', { lineHeight: '1.875rem', letterSpacing: '-0.02em', fontWeight: '500' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.625rem', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.375rem', letterSpacing: '0.005em', fontWeight: '400' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.08em', fontWeight: '500' }],
        'label-sm': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.1em', fontWeight: '400' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'space-2xl': '4rem',
        'space-3xl': '6rem',
        margin: '1.5rem',
        'margin-md': '3rem',
        'margin-lg': '5rem',
        gutter: '1.5rem',
        'gutter-lg': '2.5rem',
      },
      maxWidth: {
        '1360': '1360px',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgb(17 17 17 / 0.05)',
        md: '0 4px 6px -1px rgb(17 17 17 / 0.08)',
      },
      borderRadius: {
        none: '0px',
      },
    },
  },
  plugins: [],
};

export default config;
